/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "outline": "var(--color-outline)",
        "secondary-fixed": "var(--color-secondary-fixed)",
        "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)",
        "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
        "primary-fixed": "var(--color-primary-fixed)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "on-background": "var(--color-on-background)",
        "on-secondary": "var(--color-on-secondary)",
        "primary": "var(--color-primary)",
        "surface-container": "var(--color-surface-container)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "surface-container-low": "var(--color-surface-container-low)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim)",
        "on-tertiary-container": "var(--color-on-tertiary-container)",
        "surface-bright": "var(--color-surface-bright)",
        "secondary": "var(--color-secondary)",
        "on-primary-fixed": "var(--color-on-primary-fixed)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "outline-variant": "var(--color-outline-variant)",
        "on-error": "var(--color-on-error)",
        "on-tertiary": "var(--color-on-tertiary)",
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
        "tertiary": "var(--color-tertiary)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",
        "surface-tint": "var(--color-surface-tint)",
        "error": "var(--color-error)",
        "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)",
        "on-error-container": "var(--color-on-error-container)",
        "on-primary": "var(--color-on-primary)",
        "surface-variant": "var(--color-surface-variant)",
        "on-primary-container": "var(--color-on-primary-container)",
        "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
        "background": "var(--color-background)",
        "error-container": "var(--color-error-container)",
        "primary-container": "var(--color-primary-container)",
        "surface-container-high": "var(--color-surface-container-high)",
        "inverse-on-surface": "var(--color-inverse-on-surface)",
        "tertiary-container": "var(--color-tertiary-container)",
        "on-secondary-container": "var(--color-on-secondary-container)",
        "inverse-primary": "var(--color-inverse-primary)",
        "tertiary-fixed": "var(--color-tertiary-fixed)",
        "surface-dim": "var(--color-surface-dim)",
        "on-surface": "var(--color-on-surface)",
        "secondary-container": "var(--color-secondary-container)",
        "inverse-surface": "var(--color-inverse-surface)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed)",
        "surface": "var(--color-surface)",
      },
      fontFamily: {
        'headline-xl': ['Lexend', 'sans-serif'],
        'body-md': ['Lexend', 'sans-serif'],
        'label-sm': ['Lexend', 'sans-serif'],
        'headline-md': ['Lexend', 'sans-serif'],
        'body-lg': ['Lexend', 'sans-serif'],
        'headline-lg': ['Lexend', 'sans-serif'],
        'label-md': ['Lexend', 'sans-serif'],
        lexend: ['Lexend', 'sans-serif']
      },
      spacing: {
        "gutter": "24px",
        "element-gap": "12px",
        "section-gap": "48px",
        "container-margin": "32px",
        "unit": "8px",
        "card-padding": "24px"
      }
    },
  },
  plugins: [],
}
